/*
 * MiscTicketItemDialog.java
 *
 * Created on September 8, 2006, 10:04 PM
 */

package com.floreantpos.ui.dialog;

import java.awt.FlowLayout;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

import net.miginfocom.swing.MigLayout;


import com.floreantpos.main.Application;
import com.floreantpos.model.MenuItem;
import com.floreantpos.swing.ComboBoxModel;
import com.floreantpos.swing.PosComboRenderer;
import com.floreantpos.ui.TitlePanel;

/**
 *
 * @author  Vinay Gupta
 */
public class SelectItemFromDropDownDialog extends POSDialog {
	private List<MenuItem> menuItems;
	private MenuItem finalMenuItem;

	/** Creates new form SelectItemFromDropDownDialog */
	public SelectItemFromDropDownDialog(List<MenuItem> menuItems) {
		super(Application.getPosWindow(), true);
		this.menuItems = menuItems;
		setTitle("Select specific item");
		
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		JPanel contentPane = new JPanel(new MigLayout("fillx", "", ""));

		TitlePanel titlePanel = new TitlePanel();
		titlePanel.setTitle("Select item from your search result");
		contentPane.add(titlePanel, "grow, span");
		
		PosComboRenderer comboRenderer = new PosComboRenderer();
		comboRenderer.setEnableDefaultValueShowing(false);

		contentPane.add(new JLabel("Select Item"), "alignx trailing");

		cbSelectedItems = new JComboBox();
		cbSelectedItems.setRenderer(comboRenderer);
		contentPane.add(cbSelectedItems, "w 200!, h 40");
				
		contentPane.add(new JSeparator(JSeparator.HORIZONTAL), "newline, grow, span, gaptop 10px");
		
		btnOk = new com.floreantpos.swing.PosButton();
        btnOk.setText(com.floreantpos.POSConstants.OK.toUpperCase());
        btnOk.setPreferredSize(new java.awt.Dimension(120, 50));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doFinish(evt);
            }
        });
        
        btnCancel = new com.floreantpos.swing.PosButton();
        btnCancel.setText(com.floreantpos.POSConstants.CANCEL.toUpperCase());
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 50));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCancel(evt);
            }
        });
        
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        buttonPanel.add(btnOk);
        buttonPanel.add(btnCancel);
        
        contentPane.add(buttonPanel, "newline, grow, span");
		
		getContentPane().add(contentPane);
		
		initData();
	}// </editor-fold>//GEN-END:initComponents

	private void initData() {
		
		cbSelectedItems.setModel(new ComboBoxModel(menuItems));
	}

	private void doCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCancel
		setCanceled(true);
		finalMenuItem = null;
		dispose();
	}//GEN-LAST:event_doCancel

	private void doFinish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doFinish
		
		setCanceled(false);
		
		finalMenuItem = (MenuItem) cbSelectedItems.getSelectedItem();

		dispose();
	}//GEN-LAST:event_doFinish

	/**
	 * @return the finalMenuItem
	 */
	public MenuItem getFinalMenuItem() {
		return finalMenuItem;
	}



	// Variables declaration - do not modify//GEN-BEGIN:variables
	private com.floreantpos.swing.PosButton btnOk;
	private com.floreantpos.swing.PosButton btnCancel;
	// End of variables declaration//GEN-END:variables
	private JComboBox cbSelectedItems;

}
